data :
  name: MVTec  #MVTec #MTD #VisA 
  data_dir: /media/sdb/liutao/CV/data/mvtec_anomaly_detection  #MVTec #VisA #MTD  
  category: bottle  #['carpet', 'bottle', 'hazelnut', 'leather', 'cable', 'capsule', 'grid', 'pill', 'transistor', 'metal_nut', 'screw','toothbrush', 'zipper', 'tile', 'wood']    
                   # ['candle', 'capsules', 'cashew', 'chewinggum', 'fryum', 'macaroni1', 'macaroni2', 'pcb1', 'pcb2' ,'pcb3', 'pcb4', 'pipe_fryum']
  image_size: 224 
  shot: 2 # num samples of few shot
  batch_size: 32 # 32 for DDAD and 16 for DDADS
  DA_batch_size: 16 #16 for MVTec and [macaroni2, pcb1] in VisA, and 32 for other categories in VisA
  test_batch_size: 16 #16 for MVTec, 32 for VisA
  mask : True 
  input_channel : 3



model:
  device: 'cuda'
  num_workers : 4
  epochs: 50
  lr: 0.0001
  momentum: 0.9
  stn_mode: 'rotation_scale'